CREATE TABLE `lesson_schedule` (
                                   `id` int NOT NULL AUTO_INCREMENT,
                                   `sid` int NOT NULL DEFAULT '0' COMMENT '校校课表id',
                                   `clzid` int NOT NULL DEFAULT '0' COMMENT '班级 ID',
                                   `courseid` int NOT NULL DEFAULT '0' COMMENT '课程 ID',
                                   `campusid` int NOT NULL DEFAULT '0' COMMENT '校区 ID',
                                   `clzName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '班级名称',
                                   `courseName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '课程名称',
                                   `campusname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '校区名称',
                                   `organizationid` int NOT NULL DEFAULT '0' COMMENT '组织id',
                                   `content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '上课内容',
                                   `starttime` bigint NOT NULL DEFAULT '0' COMMENT '开始时间戳',
                                   `endtime` bigint NOT NULL DEFAULT '0' COMMENT '结束时间戳',
                                   `way` int NOT NULL DEFAULT '0' COMMENT '上课方式 1线下2线上',
                                   `placeId` int NOT NULL DEFAULT '0' COMMENT '上课地点id',
                                   `place` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '上课地点名称',
                                   `note` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
                                   `duration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '上课时长',
                                   `classtype` int NOT NULL DEFAULT '0' COMMENT '班级类型',
                                   `coursetype` int NOT NULL DEFAULT '0' COMMENT '课程类型',
                                   `courseCategory` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '课程分类',
                                   `category` int NOT NULL DEFAULT '0' COMMENT '类别',
                                   `tagcindex` int NOT NULL DEFAULT '0' COMMENT '标签索引',
                                   `tagcontent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '标签内容',
                                   `status` int NOT NULL DEFAULT '0' COMMENT '上课状态0 未上课 1已上课 2已取消',
                                   `scountclz` int NOT NULL DEFAULT '0' COMMENT '班级总人数',
                                   `scountjoin` int NOT NULL DEFAULT '0' COMMENT '班级加入人数',
                                   `scountleave` int NOT NULL DEFAULT '0' COMMENT '班级离开人数',
                                   `starttimeStr` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '开始时间',
                                   `endtimeStr` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '结束时间',
                                   `teacher` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '上课老师',
                                   `clzZhujiao` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '班级助教列表',
                                   `md5Str` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '数据md5值',
                                   `version` int NOT NULL DEFAULT '0' COMMENT '版本号',
                                   `addTime` int NOT NULL DEFAULT '0',
                                   `updateTime` int NOT NULL DEFAULT '0',
                                   PRIMARY KEY (`id`),
                                   UNIQUE KEY `idx_sid` (`sid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='课程-排课表';