// Code generated by goctl. DO NOT EDIT.
package types

type Campus struct {
	Id   int64  `json:"id"`   //校区id
	Type int64  `json:"type"` //校区类型
	Name string `json:"name"` //校区名称
}

type CampusInfo struct {
	ID             int         `json:"id"`        // 校区的唯一标识符
	Name           string      `json:"name"`      // 校区名称
	OutClzRoomList []Classroom `json:"room_list"` // 校区中的教室列表
}

type CampusListResponse struct {
	ErrorInfo  ErrorInfo `json:"error_info"` //错误码
	CampusList []Campus  `json:"data"`       //校区列表
}

type CampusRoomListResponse struct {
	ErrorInfo  ErrorInfo    `json:"error_info"` //错误码
	CampusInfo []CampusInfo `json:"data"`       //校区教师列表
}

type Class struct {
	ID         int    `json:"id"`          // 课程 ID
	Name       string `json:"name"`        // 课程名称
	CampusID   int    `json:"campus_id"`   // 校区 ID
	CampusName string `json:"campus_name"` // 校区名称
	CourseID   int    `json:"course_id"`   // 课程 ID
	CourseName string `json:"course_name"` // 课程名称
	ClassType  int    `json:"class_type"`  // 课程类型（可能为空）
	Category   string `json:"category"`    // 课程类别
	Status     int    `json:"status"`      // 课程状态
}

type ClassJsonDetail struct {
	CourseId  int64           `json:"courseId"`
	ClassJson []ClassJsonInfo `json:"classJson"`
}

type ClassJsonInfo struct {
	ClassId    int64         `json:"classId"`
	SeatNum    int64         `json:"seatNum"`
	IsHd       int64         `json:"isHd"`
	IsDc       int64         `json:"isDc"`
	VideoArray VideoJsonInfo `json:"videoArray"`
}

type ClassListRequest struct {
	Search    string `json:"search,optional"`             // 搜索关键字（可能为空）
	CourseID  string `json:"course_id,optional"`          // 课程 ID（可能为空）
	CampusIDs string `json:"campus_ids,optional"`         // 校区 ID 列表
	PageID    int    `json:"page,default=1"`              // 当前页码
	PageSize  int    `json:"page_size,default=20"`        // 每页大小
	Status    int    `json:"status,options=[-1,0,1,2,3]"` // 状态
}

type ClassListResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误码
	Pages     Pages     `json:"page_info"`  //页面信息
	ClassList []Class   `json:"data"`       //班级列表
}

type ClassSearchKey struct {
	KeyName  string `json:"keyName"`
	KeyValue string `json:"keyValue"`
}

type Classroom struct {
	ID   int    `json:"id"`   // 教室的唯一标识符
	Name string `json:"name"` // 教室名称
}

type Course struct {
	ID             int    `json:"id"`              // 课程 ID
	Name           string `json:"name"`            // 课程名称
	Classification string `json:"class_ification"` // 课程分类
	Category       int    `json:"category"`        // 课程类别
	Description    string `json:"description"`     // 描述
	Pics           string `json:"pics"`            // 图片
}

type CourseData struct {
	TotalClassNum int64                  `json:"total"`
	ClassList     []CourseResponseCourse `json:"class_list"`
}

type CourseList struct {
	CourseId  int64           `json:"courseId"`
	ClassJson []ClassJsonInfo `json:"classJson"`
}

type CourseRequest struct {
	ClassName       string `json:"class_name,optional"`
	CourseName      string `json:"course_name,optional"`
	TeacherName     string `json:"teacher_name,optional"`
	TeacherMobile   int64  `json:"teacher_mobile,optional"`
	CourseStartDate int64  `json:"course_start_date,optional"`
	CourseEndDate   int64  `json:"course_end_date,optional"`
	SeatNum         int64  `json:"seat_num,optional"`
	IsHd            int64  `json:"is_hd,optional"`
	Page            int    `json:"page,default=1"`
	PageSize        int    `json:"prepage,default=20"`
}

type CourseResponse struct {
	ErrorInfo ErrorInfo  `json:"error_info"`
	Data      CourseData `json:"data"`
}

type CourseResponseCourse struct {
	ClassId        int64                     `json:"class_id"`
	CourseId       int64                     `json:"course_id"`
	ClassName      string                    `json:"class_name"`
	CourseName     string                    `json:"course_name"`
	ClassStartTime int64                     `json:"class_start_time"`
	ClassEndTime   int64                     `json:"class_end_time"`
	TeacherInfo    CourseResponseTeacherInfo `json:"teacher_info"`
	SyncStatus     int64                     `json:"sync_status"`
	SeatNum        int64                     `json:"seat_num"`
	IsHd           int64                     `json:"is_hd"`
	SyncStatusName string                    `json:"sync_status_name"`
}

type CourseResponseTeacherInfo struct {
	Mobile string `json:"mobile"`
	Name   string `json:"name"`
}

type CoursesResponse struct {
	ErrorInfo  ErrorInfo `json:"error_info"` //错误码
	CourseList []Course  `json:"data"`       //课程列表
}

type CustomerBasicData struct {
	Id            int64  `json:"id"`             //客户ID
	Name          string `json:"name"`           //客户名称
	Type          int64  `json:"type"`           //客户类型  1 有效客户 2 在途客户 3 公海池
	CustomerStage int64  `json:"customer_stage"` // 客户阶段 1线索 2资源 3商机 4已签约客户 5商机待确认
}

type CustomerBasicResponse struct {
	ErrorInfo ErrorInfo           `json:"error_info"` //错误码
	Data      []CustomerBasicData `json:"data"`       //客户信息
}

type CustomerRequest struct {
	Ids []int64 `json:"ids"` // 客户ID
}

type DeleteFileByIdReq struct {
	Id int64 `json:"id"` // 文件ID
}

type DeleteFileByUUIDReq struct {
	Uuid string `json:"uid"` // 文件UUID
}

type DeleteFileResp struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误码
}

type ErrorInfo struct {
	ErrorCode int64  `json:"errno"` //错误码
	ErrorMsg  string `json:"error"` //错误信息
}

type ErrorResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
}

type FileAddressByUUIDReq struct {
	Uuid       string `json:"uid"`         // 文件UUID
	ExpireTime int64  `json:"expire_time"` //文件有效期
}

type FileAddressResp struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误码
	Address   string    `json:"address"`    //文件下载地址
}

type FileByIdReq struct {
	Id int64 `json:"id"` // 文件ID
}

type FileByUUIDReq struct {
	Uuid string `json:"uid"` // 文件UUID
}

type FileInfo struct {
	Uuid     string `json:"uuid"`      // 文件uuid
	Name     string `json:"name"`      // 文件名称
	FileType string `json:"file_type"` //文件类型
}

type FileInfoResp struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误码
	FileInfo  FileInfo  `json:"file_info"`  //文件信息
}

type FileSignUrlRequest struct {
	FileKey string `form:"fileKey"`
}

type FileSignUrlResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
	Url       string    `json:"url"`
}

type FileViewByUUIDReq struct {
	Uuid       string `json:"uid"`                               //文件id
	ExpireTime int64  `json:"expire_time,optional,default=3600"` //token 有效期
}

type FileViewInfo struct {
	Token   string `json:"token"`        //文件下载地址
	Name    string `json:"name"`         //文件名称
	Key     string `json:"file_key"`     //文件key
	Address string `json:"file_address"` //文件地址
	Type    string `json:"file_type"`    //文件类型
}

type FileViewResp struct {
	ErrorInfo    ErrorInfo    `json:"error_info"`     //错误码
	FileViewInfo FileViewInfo `json:"file_view_info"` //文件预览信息
}

type LessonClipFile struct {
	ClassId        int64  `json:"class_id"`
	CourseId       int64  `json:"course_id"`
	FileId         string `json:"file_id"`
	SequenceNumber int64  `json:"sequence_number"`
	FileName       string `json:"file_name"`
	OriginUrl      string `json:"origin_url"`
	Objectkey      string `json:"object_key"`
	FileSize       int64  `json:"file_size"`
	FileStatus     int64  `json:"file_status"`
	FileStatusName string `json:"file_status_name"`
}

type LessonClipResponse struct {
	ErrorInfo ErrorInfo         `json:"error_info"`
	VodInfo   LessonClipVodInfo `json:"data"`
}

type LessonClipSyncReq struct {
	UserAgent  string `json:"user_agent"`
	ClassId    int64  `json:"class_id,"`
	CourseId   int64  `json:"course_id"`
	Cookie     string `json:"cookie"`
	SourceType int64  `json:"source_type"`
}

type LessonClipVodInfo struct {
	AllCount   int64            `json:"all_count"`
	LessonInfo LessonInfo       `json:"lesson_info"`
	FileList   []LessonClipFile `json:"file_list"`
}

type LessonInfo struct {
	CourseName string `json:"course_name"`
	ClassName  string `json:"class_name"`
}

type LessonSyncJobReq struct {
	UserAgent       string `json:"user-agent"`
	ClassName       string `json:"class_name"`
	CourseName      string `json:"course_name"`
	CourseStartDate int64  `json:"course_start_date"`
	CourseEndDate   int64  `json:"course_end_date"`
	Cookie          string `json:"cookie"`
	Total           int64  `json:"total"`
	SourceType      int64  `json:"source_type"`
}

type LessonSyncReq struct {
	UserAgent      string `json:"user-agent"`
	ClassId        int64  `json:"class_id"`
	CourseId       int64  `json:"course_id"`
	ClassName      string `json:"class_name"`
	CourseName     string `json:"course_name"`
	ClassStartTime int64  `json:"class_start_time"`
	ClassEndTime   int64  `json:"class_end_time"`
	TeacherName    string `json:"teacher_name"`
	TeacherMobile  string `json:"teacher_mobile"`
	Cookie         string `json:"cookie"`
	SourceType     int64  `json:"source_type"`
	SeatNum        int64  `json:"seat_num"`
	IsHd           int64  `json:"is_hd"`
	IsDc           int64  `json:"is_dc"`
}

type LesssonClipRequest struct {
	ClassId  int64 `json:"class_id,"`
	CourseId int64 `json:"course_id"`
	Page     int   `json:"page,default=1"`
	PageSize int   `json:"prepage,default=20"`
}

type LoginRequest struct {
	Cookie string `json:"classin-Authorization"`
}

type LoginResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
}

type Pages struct {
	Total    int `json:"total"`     // 总记录数
	PageSize int `json:"page_size"` // 每页大小
	PageID   int `json:"page"`      // 当前页码
	Pages    int `json:"pages"`     // 总页数
}

type PdfInfo struct {
	FileUrl   string `json:"file_url"`  //文件url
	ObjecktId string `json:"object_id"` //对象id
}

type Person struct {
	ID             int64       `json:"id"`             // 用户 ID
	OrganizationID int64       `json:"organizationid"` // 组织 ID
	Name           string      `json:"name"`           // 姓名
	Mobile         string      `json:"mobile"`         // 手机号
	Role           int64       `json:"role"`           // 角色
	Teaching       interface{} `json:"teaching"`       // 未使用
	PhotoURL       interface{} `json:"photourl"`       // 图片链接
	WeChat         interface{} `json:"wechat"`         // 微信号
	Gender         interface{} `json:"gender"`         // 性别
	Introduce      interface{} `json:"introduce"`      // 介绍
	ClassInUID     int64       `json:"classinuid"`     // 班级 ID
	Token          interface{} `json:"token"`          // 认证值
	GzhVC          interface{} `json:"gzhvc"`          // 未使用
	FeedBack       interface{} `json:"feedBack"`       // 反馈
	AccPriosList   interface{} `json:"accPriosList"`   // 账户列表
}

type ScheduleExportRequest struct {
	Search     string `json:"search,optional"`       //搜索上课内容
	Status     string `json:"status,optional"`       //上课状态
	CampusIDs  string `json:"campus_ids,optional"`   //校区ID
	ClassIDs   string `json:"class_ids,optional"`    //班级ID
	TeacherIds string `json:"teacher_ids,optional"`  //教师ID
	CourseIDs  string `json:"course_ids,optional"`   //课程ID
	ZhuJiaoID  string `json:"zhujiao_id,optional"`   //主讲教师ID
	ClzRooms   string `json:"clz_rooms,optional"`    //教室ID
	Dfrom      string `json:"dfrom,optional"`        //开始时间
	Dto        string `json:"dto,optional"`          //截止时间
	PageID     int    `json:"page_id,default=1"`     //当前页码
	PageSize   int    `json:"page_size,default=10"`  //每页大小
	ExceptNull int64  `json:"except_null,default=1"` //排除空
	ShowCancel int64  `json:"show_cancel,default=1"` //显示已取消
	ViewType   int64  `json:"view_type,default=0"`   //显示类型
	Asc        int64  `json:"asc,default=1"`         //排序
	Dlall      int    `json:"dlall,default=1"`       //是否全部
}

type ScheduleExportResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误码
	Pages     Pages     `json:"page_info"`  //页面信息
	Url       string    `json:"url"`        //文件地址
}

type ScheduleJobSyncReq struct {
	Search     string `json:"search,optional"`       //搜索备注或者上课内容
	Dfrom      string `json:"dfrom,optional"`        //开始时间
	Dto        string `json:"dto,optional"`          //截止时间
	PageID     int    `json:"page_id,default=1"`     //当前页码
	PageSize   int    `json:"page_size,default=10"`  //每页大小
	Status     string `json:"status,optional"`       //上课状态
	CampusIDs  string `json:"campus_ids,optional"`   //校区ID,多个逗号分隔
	ClassIDs   string `json:"class_ids,optional"`    //班级ID,多个逗号分隔
	TeacherIds string `json:"teacher_ids,optional"`  //教师ID,多个逗号分隔
	CourseIDs  string `json:"course_ids,optional"`   //课程ID
	ZhuJiaoID  string `json:"zhujiao_id,optional"`   //主讲教师ID,多个逗号分隔
	ClzRooms   string `json:"clz_rooms,optional"`    //教室ID
	ExceptNull int64  `json:"except_null,default=1"` //排除空
	ShowCancel int64  `json:"show_cancel,default=1"` //显示已取消
	ViewType   int64  `json:"view_type,default=0"`   //显示类型
	Asc        int64  `json:"asc,default=1"`         //排序
}

type ScheduleSyncRequest struct {
	Search     string `json:"search,optional"`       //搜索上课内容
	Status     string `json:"status,optional"`       //上课状态
	CampusIDs  string `json:"campus_ids,optional"`   //校区ID
	ClassIDs   string `json:"class_ids,optional"`    //班级ID
	TeacherIds string `json:"teacher_ids,optional"`  //教师ID
	CourseIDs  string `json:"course_ids,optional"`   //课程ID
	ZhuJiaoID  string `json:"zhujiao_id,optional"`   //主讲教师ID
	ClzRooms   string `json:"clz_rooms,optional"`    //教室ID
	Dfrom      string `json:"dfrom,optional"`        //开始时间
	Dto        string `json:"dto,optional"`          //截止时间
	PageID     int    `json:"page_id,default=1"`     //当前页码
	PageSize   int    `json:"page_size,default=10"`  //每页大小
	ExceptNull int64  `json:"except_null,default=1"` //排除空
	ShowCancel int64  `json:"show_cancel,default=1"` //显示已取消
	ViewType   int64  `json:"view_type,default=0"`   //显示类型
	Asc        int64  `json:"asc,default=1"`         //排序
}

type ScheduleSyncResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
	Data      SyncData  `json:"data"`
}

type ScheduleViewsRequest struct {
	ViewType   int64  `json:"view_type,default=0"`            // 视图类型
	Search     string `json:"search,optional"`                // 搜索上课内容关键字
	CourseIds  string `json:"course_ids,optional"`            // 课程 ID
	CampusIds  string `json:"campus_ids,optional"`            // 校区 ID
	TeacherIds string `json:"teacher_ids,optional"`           // 教师 ID
	ZhujiaoId  string `json:"zhujiao_id,optional"`            // 助教教师 ID
	ClassIds   string `json:"class_ids,optional"`             // 班级 ID
	Status     string `json:"status,optional,options=|0|1|2"` // 状态
	PageSize   int    `json:"page_size,default=2"`            // 每页大小
	PageId     int    `json:"page_id,default=1"`              // 页码
	ClzRooms   string `json:"clzrooms,optional"`              // 教室 ID
	ShowRange  int64  `json:"show_range,optional"`            // 显示排课类型
	ExceptNull int64  `json:"except_null,default=1"`          // 是否显示空课
	ShowCancel int64  `json:"show_cancel,default=1"`          // 是否显示已取消
	Asc        int64  `json:"asc,default=0"`                  // 升序 1 降序 0
	Dfrom      string `json:"dfrom,optional"`                 // 日期开始
	Dto        string `json:"dto,optional"`                   // 日期结束
}

type ScheduleViewsResponse struct {
	ErrorInfo     ErrorInfo   `json:"error_info"`    //错误信息
	ConflictCount int         `json:"conflictCount"` // 冲突数量
	Pages         Pages       `json:"page_info"`     //页面信息
	ScheduleViews []ViewsData `json:"data"`          //课表
}

type SetNumInfo struct {
	ClassId    int64  `json:"class_id"`
	ClassName  string `json:"class_name"`
	ClassBtime string `json:"class_btime"`
	ErrorCode  int64  `json:"errno"`
	ErrorMsg   string `json:"error"`
}

type SetNumRequest struct {
	Cookie     string       `json:"Cookie"`
	CourseList []CourseList `json:"courseList"`
}

type SetNumResponse struct {
	ErrorInfo ErrorInfo    `json:"error_info"`
	Data      []SetNumInfo `json:"data"`
}

type SignUrl struct {
	Url string `json:"url"`
}

type SignUrlRequest struct {
	Objectkey string `json:"object_key"`
}

type SignUrlResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
	Data      SignUrl   `json:"data"`
}

type Sort struct {
	SortName  string `json:"sortName"`
	SortValue int64  `json:"sortValue"`
}

type SyncData struct {
	Search     string `json:"search,optional"`       //搜索上课内容
	Dfrom      string `json:"dfrom,optional"`        //开始时间
	Dto        string `json:"dto,optional"`          //截止时间
	PageID     int    `json:"page_id,default=1"`     //当前页码
	PageSize   int    `json:"page_size,default=10"`  //每页大小
	Status     string `json:"status,optional"`       //上课状态
	CampusIDs  string `json:"campus_ids,optional"`   //校区ID,多个逗号分隔
	ClassIDs   string `json:"class_ids,optional"`    //班级ID,多个逗号分隔
	TeacherIds string `json:"teacher_ids,optional"`  //教师ID,多个逗号分隔
	CourseIDs  string `json:"course_ids,optional"`   //课程ID,多个逗号分隔
	ZhuJiaoID  string `json:"zhujiao_id,optional"`   //主讲教师ID,多个逗号分隔
	ClzRooms   string `json:"clz_rooms,optional"`    //教室ID,多个逗号分隔
	ExceptNull int64  `json:"except_null,default=1"` //排除空
	ShowCancel int64  `json:"show_cancel,default=1"` //显示已取消
	ViewType   int64  `json:"view_type,default=0"`   //显示类型
	Asc        int64  `json:"asc,default=1"`         //排序
	Total      int    `json:"total"`                 //总数
}

type SyncLessonInfo struct {
	ClassName       string `json:"class_name"`
	CourseName      string `json:"course_name"`
	CourseStartDate int64  `json:"course_start_date"`
	CourseEndDate   int64  `json:"course_end_date"`
	Total           int64  `json:"total"`
}

type SyncLessonRequest struct {
	ClassName       string `json:"class_name,optional"`
	CourseName      string `json:"course_name,optional"`
	CourseStartDate int64  `json:"course_start_date"`
	CourseEndDate   int64  `json:"course_end_date"`
	Cookie          string `json:"cookie"`
}

type SyncLessonResponse struct {
	ErrorInfo ErrorInfo      `json:"error_info"`
	Data      SyncLessonInfo `json:"data"`
}

type Teacher struct {
	ID             int    `json:"id"`              // 用户 ID
	OrganizationID int    `json:"organization_id"` // 组织 ID
	Password       string `json:"password"`        // 密码
	Name           string `json:"name"`            // 姓名
	Role           int    `json:"role"`            // 角色
	Mobile         string `json:"mobile"`          // 手机号
	Teaching       string `json:"teaching"`        // 教学信息（可能为空）
	Username       string `json:"username"`        // 用户名
	SysUse         bool   `json:"sysuse"`          // 系统使用标志
	PhotoURL       string `json:"photo_url"`       // 照片 URL（可能为空）
	Wechat         string `json:"wechat"`          // 微信（可能为空）
	Gender         string `json:"gender"`          // 性别（可能为空）
	Introduce      string `json:"introduce"`       // 介绍（可能为空）
	TeachLength    string `json:"teach_length"`    // 教学时长（可能为空）
	TeachStyle     string `json:"teach_style"`     // 教学风格（可能为空）
	City           string `json:"city"`            // 城市（可能为空）
	PhotoPro       string `json:"photo_pro"`       // 照片专业（可能为空）
	VideoPro       string `json:"video_pro"`       // 视频专业（可能为空）
	ShowYangyu     bool   `json:"show_Yangyu"`     // 是否显示杨语
	ShowExpYangyu  bool   `json:"showExp_Yangyu"`  // 是否显示杨语经验
	ClassInUID     int    `json:"classin_uid"`     // ClassIn 用户 ID
	BDel           bool   `json:"bdel"`            // 删除标志
	RAccountID     int    `json:"raccount_id"`     // 账户 ID（可能为空）
	TeaDuration    string `json:"tea_duration"`    // 教学持续时间
	Token          string `json:"token"`           // 令牌（可能为空）
	Gzhvc          string `json:"gzhvc"`           // 公众号验证（可能为空）
	AccPriosList   string `json:"acc_prios_list"`  // 账户优先级列表（可能为空）
	Disabled       bool   `json:"disabled"`        // 是否禁用
	JustRecovery   bool   `json:"just_recovery"`   // 是否刚恢复
}

type TeacherAssistantsResponse struct {
	ErrorInfo     ErrorInfo `json:"error_info"` //错误码
	Pages         Pages     `json:"page_info"`  //页数
	AssistantList []Teacher `json:"data"`       //助教列表
}

type TeacherReq struct {
	PageId   int `json:"page,default=1"`        //页码 默认 1
	PageSize int `json:"page_size,default=999"` //页码大小 默认999
}

type TeacherServiceMapData struct {
	TeacherId           int     `json:"teacher_id"`            //老师id
	TeacherName         string  `json:"teacher_name"`          //老师姓名
	TeacherPhone        string  `json:"teacher_phone"`         //老师手机号
	CooperationTypeId   int     `json:"cooperation_type_id"`   //1全职2兼职
	CooperationTypeName string  `json:"cooperation_type_name"` //全职或兼职
	ServiceTypeId       int     `json:"service_type_id"`       //服务类型id
	ServiceTypeName     string  `json:"service_type_name"`     //服务业务,例如:语培/择校
	CategoryId          int     `json:"category_id"`           //服务科目id
	CategoryName        string  `json:"category_name"`         //服务科目,例如:雅思/托福
	ItemId              int     `json:"item_id"`               //服务内容id
	ItemName            string  `json:"item_name"`             //服务内容,例如:听力/口语
	Price               float64 `json:"price"`                 //服务价格
}

type TeacherServiceMapRequest struct {
	Id    int    `json:"id,optional"` //老师id
	Phone string `json:"phone"`       //老师手机号
}

type TeacherServiceMapResponse struct {
	ErrorInfo ErrorInfo               `json:"error_info"` //错误信息
	Data      []TeacherServiceMapData `json:"data"`       //老师服务列表数据
}

type TeacherTypeData struct {
	Id             int    `json:"id"`             //老师id
	Phone          string `json:"phone"`          //老师手机号
	CoopLavel      string `json:"coopLavel"`      //老师类型名称
	CoopLavelValue int    `json:"coopLavelValue"` //老师类型值
}

type TeacherTypeRequest struct {
	MultiPhone string `json:"multi_phone"`
}

type TeacherTypeResponse struct {
	ErrorInfo ErrorInfo         `json:"error_info"` //错误信息
	Data      []TeacherTypeData `json:"data"`       //老师类型列表数据
}

type TeachersResponse struct {
	ErrorInfo   ErrorInfo `json:"error_info"` //错误码
	Pages       Pages     `json:"page_info"`  //页数
	TeacherList []Teacher `json:"data"`       //教师列表
}

type TimeRange struct {
	StartTime int64 `json:"startTime"`
	EndTime   int64 `json:"endTime"`
}

type TokenErrorInfo struct {
	ErrorCode int64  `json:"code"` //错误码
	ErrorMsg  string `json:"msg"`  //错误信息
}

type UrlToPdfRequest struct {
	Url      string  `json:"url"`                      //老师id
	Delay    int64   `json:"delay,default=0"`          //延迟时间
	Scale    float64 `json:"scale,default=1"`          //老师手机号
	FileName string  `json:"file_name,default=output"` //文件名称
}

type UrlToPdfResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误信息
	Data      PdfInfo   `json:"data"`       //老师服务列表数据
}

type VideoJsonInfo struct {
	RecordState int64 `json:"recordState"`
	OpenState   int64 `json:"openState"`
}

type ViewsData struct {
	ID                    int64         `json:"id"`                    // 排课的唯一标识符
	LockVersion           int64         `json:"lockversion"`           // 排课的锁版本
	ClzID                 int64         `json:"clzid"`                 // 班级 ID
	OrganizationID        int64         `json:"organizationid"`        // 组织 ID
	CourseID              int64         `json:"courseid"`              // 课程 ID
	Teacher               Person        `json:"teacher"`               // 教师信息
	StartTime             int64         `json:"starttime"`             // 开始时间
	EndTime               int64         `json:"endtime"`               // 结束时间
	Way                   int64         `json:"way"`                   // 排课方式
	Content               string        `json:"content"`               // 上课内容
	Place                 string        `json:"place"`                 // 上课地点
	CoopLevelValue        int           `json:"coopLevelValue"`        //兼职分级数值
	CoopLevel             string        `json:"coopLevel"`             // 兼职分级名称
	URLTeacher            interface{}   `json:"urlteacher"`            // 教师链接
	URLStudent            interface{}   `json:"urlstudent"`            // 学生链接
	Note                  interface{}   `json:"note"`                  // 备注
	Duration              string        `json:"duration"`              // 时长
	DurationMinutes       int64         `json:"durationminutes"`       // 时长（分钟）
	Knowledge             interface{}   `json:"knowledge"`             // 知识点
	Training              interface{}   `json:"training"`              // 培训
	Scene                 interface{}   `json:"scene"`                 // 场景
	GenseeID              interface{}   `json:"genseeid"`              // GenSee ID
	FromSmart             bool          `json:"fromsmart"`             // 是否来自智能排课
	TDay                  int64         `json:"tday"`                  // 星期
	Category              int64         `json:"category"`              // 分类
	CourseType            int64         `json:"coursetype"`            // 课程类型
	TagContent            string        `json:"tagcontent"`            // 标签内容
	TagCIndex             int64         `json:"tagcindex"`             // 标签索引
	Adjusts               []interface{} `json:"adjusts"`               // 调整
	Ended                 bool          `json:"ended"`                 // 是否已结束
	LiveRcds              interface{}   `json:"livercds"`              // 直播记录
	IsConflict            bool          `json:"isconflict"`            // 是否冲突
	PreoccupyConflict     bool          `json:"preoccupyconflict"`     // 是否被占用
	StudentConflict       bool          `json:"studentconflict"`       // 是否学生冲突
	IgnorePerfms          interface{}   `json:"ignoreperfms"`          // 未使用
	CorpwxScheduleID      interface{}   `json:"corpwxScheduleId"`      // 未使用
	IFromSmart            bool          `json:"ifromsmart"`            // 是否来自智能排课
	Status                int64         `json:"status"`                // 状态
	PlaceID               interface{}   `json:"placeId"`               // 教室 ID
	EdStatus              bool          `json:"edstatus"`              // 是否已结束
	Attendanced           bool          `json:"attendanced"`           // 是否已签到
	Attendance            int64         `json:"attendance"`            // 签到状态
	SCountClz             int64         `json:"scountclz"`             // 已加入
	SCountJoin            int64         `json:"scountjoin"`            // 已签到
	SCountLeave           int64         `json:"scountleave"`           // 已请假
	StartTimeStr          string        `json:"starttimeStr"`          // 开始时间
	EndTimeStr            string        `json:"endtimeStr"`            // 结束时间
	CourseName            string        `json:"courseName"`            // 课程名称
	CourseCategory        string        `json:"courseCategory"`        // 课程分类
	ClzName               string        `json:"clzName"`               // 班级名称
	ScheduleCount         int64         `json:"scheduleCount"`         // 课表数量
	PerformanceInSchedule interface{}   `json:"performanceInSchedule"` // 未使用
	URLAssistant          interface{}   `json:"urlassistant"`          // 助教教师
	IngStatus             int64         `json:"ingstatus"`             // 当前用户状态
	Adjust                interface{}   `json:"adjust"`                // 未使用
	ClassType             int64         `json:"classtype"`             // 班级类型
	Force                 interface{}   `json:"force"`                 // 未使用
	CampusID              int64         `json:"campusid"`              // 校区 ID
	CampusName            interface{}   `json:"campusname"`            // 校区名字
	Conficts              interface{}   `json:"conficts"`              // 冲突课程
	TheSmart              bool          `json:"thesmart"`              // 是否来自智能排课
	ClzZhujiao            interface{}   `json:"clzZhujiao"`            // 助教教师
	ViewSrc               interface{}   `json:"viewsrc"`               // 未使用
	DisEditable           bool          `json:"diseditable"`           // 是否可编辑
	PeriodOfClz           float64       `json:"periodOfClz"`           // 班级时长
	PeriodOfCur           float64       `json:"periodOfCur"`           // 当前课程时长
	ClassPlatform         int64         `json:"classplatform"`         // 班级平台
	DayList               interface{}   `json:"dayList"`               // 未使用
	ScheduleType          interface{}   `json:"scheduleType"`          // 排课类型
	TeacherID             interface{}   `json:"teacherid"`             // 教师 ID
}
